# -*- coding: utf-8 -*-
"""ps4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_tK-RHQjl0wolRpdcyILPfMtWDryYLKg
"""

import random
from scipy.stats import norm, sem, zscore, beta
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from tabulate import tabulate

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <h2> Sorting in Python Pandas</h2>
# <h3>DataFrame.sort_values()</h3>
# <p> Nuona Chen</p>
# <p> nuona@umich.edu </p>

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <h2>DataFrame.sort_values()</h2>
# <h3>General Form</h3>
# <li>DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)</li>
# 
# <h3>What it does</h3>
# <li>sorts the input DataFrame by values</hi>
# 
# <h3>Input Parameters</h3>
#   <li>by: name or list of names to sort by</li>
#   <li>axis: 0 -> sort indices, 1 -> sort columns </li>
#   <li>ascending: true -> sort ascending, false -> sort descending</li>
#   <li>inplace: true -> sort in-place </li>
#   <li>kind: sorting algorithm </li>
#   <li>na_position: first -> put NaNs at the beginning, last -> put NaNs at the end</li>
#   <li>ignore_index: true -> label axis as 0, 1,..., n-1</li>
# 
# <h3>Function Output</h3>
# <li>The sorted Pandas DataFrame</li>
# <h4>Reference: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html</h4>

from IPython.core.display import HTML, display
display(HTML('<h2>Example1 - Sort by Columns</h2>'))

data = {"id": [1, 2, 3, 4, 5, 6],
        "gpa": [3.2, 3.7, 3.1, 3.0, 3.7, 3.7],
        "total credit hours": [55, 68, 100, 94, 46, 110],
        "major": ["Statistics", "Anthropology", "Business", "Computer Science", "Business", "Statistics"]}
print("Input DataFrame - ie_data: ")
ie_data = pd.DataFrame(data)
print(ie_data)

display(HTML('<h3>Sort by gpa in an ascending order</h3>'))
display(HTML("<code>ie_data.sort_values(by='gpa', ascending=True)</code>"))

print(ie_data.sort_values(by="gpa", ascending=True))

display(HTML('<h3>Sort by gpa and major in an descending order</h3>'))
display(HTML("<code>ie_data.sort_values(by=['gpa', 'major'], ascending=[False, True])</code>"))

print(ie_data.sort_values(by=["gpa", "major"], ascending=[False, True]))
display(HTML('<p>The order of variables in the by statement is the order of sorting. Major is sorted after gpa is sorted.</p>'))

display(HTML('<h2>Example2 - Sort by Rows</h2>'))

del ie_data["major"]
print("Input DataFrame - ie_data: ")
print(ie_data)
display(HTML('<h3>Sort by the row with index = 4 in an descending order</h3>'))
display(HTML("<code>ie_data.sort_values(by=4, axis=1, ascending=False)</code>"))

ie_data.sort_values(by=4, axis=1, ascending=False)
